### ISSUE TITLE
Error when creating conda env using the given commands 

### ISSUE THREAD

**Issue by peterstratton** [UMich-CURLY/NeuralBKI#6]
Hello, 

I'm attempting to use this repo for a class project. When I try to make the conda env using the commands
`conda env create -f environment.yml
conda activate NeuralBKI
`
I receive this error:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - fonttools==4.33.3=py37h540881e_0
  - fontconfig==2.14.0=h8e229c2_0
  - qt==5.9.7=h5867ecd_1
  - pillow==7.2.0=py37h718be6c_2
  - sqlite==3.38.5=hc218d9a_0
  - ncurses==6.3=h7f8727e_2
  - brotlipy==0.7.0=py37h27cfd23_1003
  - lame==3.100=h7b6447c_0
  - psutil==5.9.1=py37h540881e_0
  - zlib==1.2.12=h7f8727e_2
  - cudatoolkit==11.3.1=h2bc3f7f_2
  - jpeg==9e=h7f8727e_0
  - libpng==1.6.37=hbc83047_0
  - lz4-c==1.9.3=h295c915_1
  - pyyaml==6.0=py37h540881e_4
  - numpy==1.21.5=py37h6c91a56_3
  - libidn2==2.3.2=h7f8727e_0
  - tk==8.6.12=h1ccaba5_0
  - icu==58.2=hf484d3e_1000
  - pcre==8.45=h9c3ff4c_0
  - openh264==2.1.1=h4ff587b_0
  - mkl_fft==1.3.1=py37hd3c417c_0
  - python==3.7.13=h12debd9_0
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - giflib==5.2.1=h7b6447c_0
  - pyqt==5.9.2=py37hcca6a23_4
  - numpy-base==1.21.5=py37ha15fc14_3
  - nettle==3.7.3=hbbd107a_1
  - intel-openmp==2021.4.0=h06a4308_3561
  - cryptography==37.0.1=py37h9ce1e76_0
  - libwebp==1.2.2=h55f646e_0
  - cffi==1.15.0=py37hd667e15_1
  - libbrotlicommon==1.0.9=h166bdaf_7
  - mkl_random==1.2.2=py37h51133e4_0
  - libxcb==1.13=h7f98852_1004
  - certifi==2022.6.15=py37h89c1867_0
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - pip==21.2.2=py37h06a4308_0
  - bzip2==1.0.8=h7b6447c_0
  - xz==5.2.5=h7f8727e_1
  - ld_impl_linux-64==2.38=h1181459_1
  - libiconv==1.16=h7f8727e_2
  - brotli==1.0.9=h166bdaf_7
  - tornado==6.1=py37h540881e_3
  - libgomp==11.2.0=h1234567_1
  - ca-certificates==2022.6.15=ha878542_0
  - gstreamer==1.14.0=h28cd5cc_2
  - lcms2==2.12=h3be6417_0
  - zstd==1.5.2=ha4553b6_0
  - docutils==0.18.1=py37h89c1867_1
  - libuv==1.40.0=h7b6447c_0
  - matplotlib==3.5.2=py37h89c1867_0
  - libffi==3.3=he6710b0_2
  - gnutls==3.6.15=he1e5248_0
  - freetype==2.11.0=h70c0345_0
  - gmp==6.2.1=h295c915_3
  - sip==4.19.8=py37hf484d3e_0
  - yaml==0.2.5=h7f98852_2
  - pthread-stubs==0.4=h36c2ea0_1001
  - unicodedata2==14.0.0=py37h540881e_1
  - xorg-libxau==1.0.9=h7f98852_0
  - libbrotlidec==1.0.9=h166bdaf_7
  - libstdcxx-ng==11.2.0=h1234567_1
  - readline==8.1.2=h7f8727e_1
  - ffmpeg==4.3=hf484d3e_0
  - _openmp_mutex==5.1=1_gnu
  - urllib3==1.26.9=py37h06a4308_0
  - openssl==1.1.1o=h7f8727e_0
  - expat==2.4.8=h27087fc_0
  - libbrotlienc==1.0.9=h166bdaf_7
  - mkl==2021.4.0=h06a4308_640
  - libwebp-base==1.2.2=h7f8727e_0
  - matplotlib-base==3.5.2=py37hc347a89_0
  - libunistring==0.9.10=h27cfd23_0
  - libxml2==2.9.14=h74e7548_0
  - libtiff==4.2.0=h2818925_1
  - pytorch==1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - libgcc-ng==11.2.0=h1234567_1
  - libuuid==2.32.1=h7f98852_1000
  - dbus==1.13.6=he372182_0
  - glib==2.69.1=h4ff587b_1
  - setuptools==61.2.0=py37h06a4308_0
  - libtasn1==4.16.0=h27cfd23_0
  - mkl-service==2.4.0=py37h7f8727e_0
  - brotli-bin==1.0.9=h166bdaf_7

Any advice on how to fix this?

Thank you!

**Comment by Alt216** [comment]
Hi, this error occurs because you did not create the conda environment yet. You will have to first create the environment using `conda env create -f environment.yml` and then you can activate the environment with `conda activate NeuralBKI`.

**Comment by Alt216** [comment]
Also what operating system are you using? The environment yaml file is set up for ubuntu 20.04.

**Comment by peterstratton** [comment]
I get the error when I run the command you recommended: `conda env create -f environment.yml`. However, I'm attempting to run this on windows. I have dual boot ubuntu 20.04, so I can attempt to run `conda env create -f environment.yml` and report back.

**Comment by Alt216** [comment]
So you have encountered this issue running on ubuntu?

**Comment by peterstratton** [comment]
Just attempted to run the above commands on Ubuntu and they worked!
