### ISSUE TITLE
Preprocessing TartanAir neighborhood dataset using ELAS to generate depth images

### ISSUE THREAD

**Issue by sandilyasg** [UMich-CURLY/NeuralBKI#7]
I see that you preprocessed the Kitti Odometry following [Yang et al.](https://github.com/shichaoy/semantic_3d_mapping/tree/master/preprocess_data#readme) and used [ELAS](https://www.cvlibs.net/software/libelas/) to generate depth images from Kitti Odometry dataset's stereo images.

I am using the TartanAir neighborhood dataset ([neighborhood_sample_P002](https://cmu.app.box.com/s/5trtb7f3ogjao33lgk6xu6t9y9nu79wg)) which is stereo and has  image_left and image_right, depth_left and depth_right data. How can I use ELAS to generate depth images from TartanAir neighborhood dataset stereo images? Is there code you can provide for this?

**Comment by Alt216** [comment]
Hi you can download the ELAS library with this [link](https://www.cvlibs.net/download.php?file=libelas.zip). In the readme file they explain how to run the library to generate the depth images. We used this directly to generate the preprocessed kitti odometry depth images.

**Comment by sandilyasg** [comment]
I installed ELAS library with the link and ran the instructions below:
Linux:

1) Move to libelas root directory
2) Type 'cmake .'
3) Type 'make'
4) Run './elas demo' => computes disparity maps for images from the 'img' directory

I now have the left and right disparity maps, but how do I generate the depth images? Do I need to perform camera calibration?

**Comment by Alt216** [comment]
Sorry I didn't realize that you have the disparity images already. You can get the depth from disparity using this formula:
depth = (baseline * focal length) / disparity) ([reference](https://stackoverflow.com/questions/61053294/what-is-difference-between-disparity-and-depth). You can loop over the disparity images pixel by pixel and compute the depth using the formula above, you will need the baseline and focal length parameters for the stereo cameras.

**Comment by tigeriv** [comment]
Marking as closed
