### ISSUE TITLE
The preprocessed data link failed

### ISSUE THREAD

**Issue by AAAAAurora** [UMich-CURLY/NeuralBKI#8]
The preprocessed data link failed and the dataset could not be downloaded. Please provide a new valid link for download. Thank you!

**Comment by tigeriv** [comment]
Thank you for your interest in our work and alerting us to this issue! I have updated the link to a more permanent download solution. Please let us know if the link does not work for you, or if you have any other difficulties using our project.

**Comment by AAAAAurora** [comment]
Great! Thank you so much.
