### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by AAAAAurora** [UMich-CURLY/NeuralBKI#9]
Hello！ How can I publish to rviz to form a map after running train.py and generate_results.py？I have modified the yaml file（visualize: True）, but there is no output display.

**Comment by tigeriv** [comment]
Hi, setting the visualize flag to True broadcasts ROS messages to rviz however you will still need to set up a roscore master and rviz GUI. For example, run in a terminal window "roscore", then in another terminal window "rviz rviz", then run the generate results script.

**Comment by AAAAAurora** [comment]
Thank you for your response and solution. The issue is now resolved!
